### ISSUE TITLE
Page not found exeption

### ISSUE THREAD

**Issue by ramnkl16** [Sitecore/Commerce-Connect-StarterKit#2]
I followed the deployment guide instructions and completed successful.  While access home page I could see tabs as given below. 
<img width="799" alt="commercehomepage" src="https://cloud.githubusercontent.com/assets/19195181/17270154/cab0241a-5621-11e6-9594-5d1b2c4f5bdb.PNG">

While access any of the tab or Registration  page I'm getting sitecore notfound.aspx page. 
Please guide to proceed further

Here is the content tree
<img width="182" alt="commercecontenttree" src="https://cloud.githubusercontent.com/assets/19195181/17270177/4a0251ac-5622-11e6-99ff-c20a725d7ee7.PNG">

**Comment by SorenKerrn** [comment]
Hi

Due to vacation time, we are a bit delayed in responding. We will test it out and get back to you

**Comment by ramnkl16** [comment]
Below is log info on clicking the product tab
20796 20:35:27 INFO  HttpModule is being initialized
16456 20:35:53 WARN  Request is redirected to document not found page. Requested
 url: /products?category=16, User: extranet\Anonymous, Website: StarterKit
Am I missing any config setting?

**Comment by SorenKerrn** [comment]
We can’t reproduce this and do not have problems clicking tabs or registration. The below builds were used.
Please confirm that the site content is present by opening the content editor. You should see a store item with 8 sub-items including "Products", which will respond to your URL. 
You need to create the site using branch template "Sample Site", by follow steps 11-18 from the [deployment topic on the Wiki](https://github.com/Sitecore/Commerce-Connect-StarterKit/wiki/Deployment-Guide).
Once the content is present, it's important that the content is published. You can check if the content is present in the Web database by changing the database in the lower right corner of the Sitecore Desktop and open the content editor.

Builds
nopCommerce 3.10
nopCommerce-Plugins.zip
Sitecore 8.1 rev. 151207.zip
Sitecore Commerce Connect 8.1 rev. 160202.zip
Sitecore.Commerce.Connect.Connectors.NopCommerce.8.1.rev.160202.zip
Sitecore.Commerce.Connect.StarterKit.8.1.rev.160202.zip
